### ISSUE TITLE
error reading countries-17.0.27 Illegal character in path

### ISSUE THREAD

**Issue by trixon** [HanSolo/countries#7]
I'm not sure if this is because of this library or nbm-maven-plugin that I use to build my NetBeansPlatform application, or anything else.

```
error reading /home/pata/.m2/repository/eu/hansolo/fx/countries/17.0.27/countries-17.0.27.jar; java.net.URISyntaxException: Illegal character in path at index 64: file:/home/pata/.m2/repository/eu/hansolo/fx/countries/17.0.27/${project.name}-${project.version}.jar
error reading /home/pata/.m2/repository/eu/hansolo/fx/heatmap/17.0.15/heatmap-17.0.15.jar; java.net.URISyntaxException: Illegal character in path at index 62: file:/home/pata/.m2/repository/eu/hansolo/fx/heatmap/17.0.15/${project.name}-${project.version}.jar

```

The manifest of countries contains
`Class-Path: ${project.name}-${project.version}.jar`
Is that by design and should it work?

**Comment by HanSolo** [comment]
That’s probably wrong, will take a look at it, thx for the report 👍🏻

**Comment by HanSolo** [comment]
I’ve released a new version where this problem should be fixed, can you give it a try?

**Comment by trixon** [comment]
Thanks, it works just fine now!

**Comment by HanSolo** [comment]
Fixed
